kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: rob
  labels:
    app: rob
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rob
        name: rob
        tier: backend
    spec:
      containers:
        - name: rob
          image: # url to image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080